

POST http://localhost:5000/
Content-Type: application/json

["femme", "homme","été", "cheveux"]


###

POST http://localhost:5000/
Content-Type: application/json

["voiture"]

###

POST http://localhost:5000/
Content-Type: application/json

["livre"]

###

POST http://localhost:5000/
Content-Type: application/json

["crème"]